[package]
name = "ddnnife"
version = "0.5.0"
authors = ["Heiko Raab; heiko.raab@uni-ulm-de", "Chico Sundermann; chico.sundermann@uni-ulm.de"]
edition = "2021"
license = "GNU LGPL-2.1"

[lib]
name = "ddnnf_lib"
path = "src/lib.rs"

[[bin]]
name = "ddnnife"
path = "src/bin/ddnnife.rs"

[[bin]]
name = "dhone"
path = "src/bin/dhone.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat" # enables link-time optimization
codegen-units = 1 # forbid parallel compiling
panic = "abort"
# for performance graphs: debug = true

[dependencies]
clap = { version = "4.1.8", features = ["cargo", "derive", "color"] }
colored = "2.0.0"
mimalloc = { version = "*", default-features = false }
rug = "1.19.1"
nom = "7.1.3"
csv = "1.2.1"
workctl = "0.2.0" # parallelisation
file_diff = "1.0.0"
petgraph = "0.6.3"
rand_pcg = "0.3.1"
rand = "0.8.5"
rand_distr = "0.4.3"
itertools = "0.10.5"
once_cell = "1.17.1"
rustc-hash = "1.1.0"
bitvec = "1.0.1"
