name: reasoner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: cargo build
      
  Doc-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Doc-tests
      run: cargo test --doc
      
  Integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Integration-tests
      run: cargo test --release --tests
